# user config file
# it allows to override connection attribute values defined by the `postgres` key
# also, it allows to define foreign servers that will be automatically created on startup

# section placeholders to override default values
# uncomment and set the values to override default value for any attribute
postgres:
#  hostname: localhost
#  port: 5432
#  database: postgres
#  username: postgres
#  password: postgres


# Example: foreign servers
# servers:
#   mongo_fdw_1:
#     description: MyServer
#     fdw_name: mongo_fdw
#     foreign_server:
#       address: hostname
#       port: 27017
#     user_mapping:
#       username: some_user
#       password: password
#
#   ...
#
#   mysql_fdw_1:
#     description: Some Project - dev
#     fdw_name: mysql_fdw
#     foreign_server:
#       host: hostname
#       port: 3306
#     user_mapping:
#       username: some_user
#       password: password
