# validation schema: schema.yaml

postgres:
  hostname: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres


# Read-only list of available FDW extensions
fdw_list:
- file_fdw
- mongo_fdw
- mysql_fdw
- oracle_fdw
- postgres_fdw
- redis_fdw
- sqlite_fdw
- tds_fdw


# FDW options template
#
# fdw_options:
#   fdw_name:
#     <categories>
#     advanced:
#       <categories>
#
# <categories> =
#   foreign_server:
#     <option>
#   user_mapping:
#     <option>
#   import_foreign_schema:
#     <option>
#   create_foreign_table:
#     <option>
#
# <option> =
#   option:
#     required: true | false
#     default:
#     description:
#     position:


# FDW options
fdw_options:
  file_fdw:
    version: 16.2.0
    create_foreign_table:
    - filename
    - program


  mongo_fdw:
    foreign_server:
      address:
        default: 127.0.0.1
        description: Address or hostname of the MongoDB server. Defaults to 127.0.0.1
        required: true
        position: 1
      port:
        default: 27017
        description: Port number of the MongoDB server. Defaults to 27017.
        required: true
        position: 2
      authentication_database:
        description: >
          Database against which user will be authenticated against.
          Only valid with password based authentication.
        required: true
        position: 3

    user_mapping:
      username:
        description: Username to use when connecting to MongoDB.
        required: true
        position: 1
      password:
        description: Password to authenticate to the MongoDB server.
        required: true
        position: 2


  mysql_fdw:
    version: 2.9.1
    foreign_server:
    - host
    - port

    user_mapping:
    - username
    - password

    # presence of empty section is required to display Import Schema tab in UI
    import_foreign_schema:


  oracle_fdw:
    foreign_server:
      dbserver:
        description: Database server connection string
        required: true
        position: 1

    user_mapping:
      user:
        description: >
          The Oracle user name for the session.
          Set this to an empty string for external authentication if you don't want to store Oracle credentials
          in the PostgreSQL database (one simple way is to use an external password store).
        required: true
        position: 1
      password:
        description: The password for the Oracle user.
        required: true
        position: 2

    import_foreign_schema:
      remote_schema:
        description: Remote schema in Oracle server to import from.
        required: true
        position: 1
      local_schema:
        description: Local schema in which imported foreign tables will be created.
        required: true
        position: 2


  sqlite_fdw:
    foreign_server:
      database:
        description: >
          Path to the filename with SQLite database.
          File must be reachable on the server's file system where HSQL is running on
        required: true
        position: 1

    import_foreign_schema:
      # Note: sqlite doesn't have schemas. to support common IMPORT FOREIGN SCHEMA syntax
      # it's required to use any dummy value for a remote_schema parameter.
      # IMPORT FOREIGN SCHEMA "some_schema" FROM SERVER sqlite_server INTO public;
      # "some_schema" has no particular meaning for sqlite and can be set to an arbitrary value.
      local_schema:
        description: The schema in which the imported foreign tables will be created.
        required: true
        position: 1


  tds_fdw:
    foreign_server:
      servername:
        description: Database server hostname
        required: true
        position: 1
      port:
        default: 1433
        description: Database port number
        required: true
        position: 2
      database:
        description: Database name
        required: true
        position: 3

    user_mapping:
      username:
        description: Username to use when connecting to the MSSQL/Sybase server.
        required: true
        position: 1
      password:
        description: Password to authenticate to the MSSQL/Sybase server.
        required: true
        position: 2

    import_foreign_schema:
      remote_schema:
        description: Remote schema in MSSQL/Sybase server to import from.
        required: true
        position: 1
      local_schema:
        description: Local schema in which imported foreign tables will be created.
        required: true
        position: 2


  postgres_fdw:
    foreign_server:
      host:
        default: 127.0.0.1
        description: Address or hostname of the PostgreSQL server. Defaults to 127.0.0.1
        required: true
        position: 1
      port:
        default: 5432
        description: Port number of the PostgreSQL server. Defaults to 5432
        required: true
        position: 2
      dbname:
        default: postgres
        description: The database name. Defaults to be the same as the user name.
        required: true
        position: 3

    user_mapping:
      user:
        default: postgres
        description: PostgreSQL user name to connect as. Defaults to postgres.
        required: true
        position: 1
      password:
        default: postgres
        description: Password to be used if the server demands password authentication. Defaults to user name.
        required: true
        position: 2

    import_foreign_schema:
      remote_schema:
        description: Remote schema in PostgreSQL server to import from.
        required: true
        position: 1
      local_schema:
        description: Local schema in which imported foreign tables will be created.
        required: true
        position: 2


  redis_fdw:
    version: 16.2.0
    foreign_server:
    - address
    - port

    user_mapping:
    - password

    create_foreign_table:
    - database
    - tabletype
    - tablekeyprefix
    - tablekeyset
    - singleton_key
