# validation schema: schema.yaml

postgres:
  hostname: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres


# Read-only list of available FDW extensions
fdw_list:
- file_fdw
- mongo_fdw
- mysql_fdw
- oracle_fdw
- postgres_fdw
- redis_fdw
- sqlite_fdw
- tds_fdw


# FDW options template
#
# fdw_options:
#   fdw_name:
#     version: x.y.z          # reference to the driver specification version. see https://github.com/chumaky/postgres-fdw-spec
#     <categories>
#     [advanced:              # advanced sections are added dynamically as part of configuration parsing.
#       <categories>]         # all non used in categories attributes from specification are considered advanced.
#
# <categories> =
#   foreign_server:
#   [- option_name
#    ...
#    - option_name]
#   user_mapping:
#   [- option_name
#    ...
#    - option_name]
#   import_foreign_schema:    # section presence, even if empty, is required to display corresponding Tab in UI
#   [- option_name
#    ...
#    - option_name]
#   create_foreign_table:
#   [- option_name
#    ...
#    - option_name]
#   foreign_table_column:
#   [- option_name
#    ...
#    - option_name]


# Read-only FDW options
fdw_options:
  file_fdw:
    version: 16.2.0
    create_foreign_table:
    - filename
    - program


  mongo_fdw:
    version: 5.5.1
    foreign_server:
    - address
    - port
    - authentication_database
    user_mapping:
    - username
    - password


  mysql_fdw:
    version: 2.9.1
    foreign_server:
    - host
    - port
    user_mapping:
    - username
    - password
    # section presence, even if empty, is required to display Import Schema tab in UI
    import_foreign_schema:


  oracle_fdw:
    version: 2.6.0
    foreign_server:
    - dbserver
    user_mapping:
    - user
    - password
    # section presence, even if empty, is required to display Import Schema tab in UI
    import_foreign_schema:


  sqlite_fdw:
    version: 2.4.0
    foreign_server:
    - database
    # section presence, even if empty, is required to display Import Schema tab in UI
    #
    # Note: sqlite doesn't have schemas. to support common IMPORT FOREIGN SCHEMA syntax
    # it's required to use any dummy value for a remote_schema parameter.
    # IMPORT FOREIGN SCHEMA "some_schema" FROM SERVER sqlite_server INTO public;
    # "some_schema" has no particular meaning for sqlite and can be set to an arbitrary value.
    import_foreign_schema:


  tds_fdw:
    version: master_2.0.3
    foreign_server:
    - servername
    - port
    - database
    user_mapping:
    - username
    - password
    # section presence, even if empty, is required to display Import Schema tab in UI
    import_foreign_schema:


  postgres_fdw:
    version: 16.2.0
    foreign_server:
    - host
    - port
    - dbname
    user_mapping:
    - user
    - password
    # section presence, even if empty, is required to display Import Schema tab in UI
    import_foreign_schema:


  redis_fdw:
    version: 16.2.0
    foreign_server:
    - address
    - port
    user_mapping:
    - password
    create_foreign_table:
    - database
    - tabletype
    - tablekeyprefix
    - tablekeyset
    - singleton_key
