# for list of available options see "default.yaml" and "schema.yaml"

# section placeholders to override default values
postgres:

fdw_list:

servers:

# Example: foreign servers
# servers:
#   server1:
#     server_name: mongo_fdw_1
#     fdw_name: mongo_fdw
#     options:
#     user_mapping:
#       username: some_user
#       password: password
#
#   ...
#
#   serverN:
#     server_name: mysql_fdw_1
#     fdw_name: mysql_fdw
#     options:
#       host: hostname
#       port: 3306
#     user_mapping:
#       username: some_user
#       password: password
