# validation schema: schema.yaml

postgres:
  hostname: localhost
  port: 5432
  database: postgres
  username: postgres
  password: postgres


fdw_list:
  file_fdw:
    enabled: true
    schema_name: file_fdw
    name: File Access
    icon: file.svg
  mongo_fdw:
    enabled: true
    schema_name: mongo_fdw
    name: MongoDB
    icon: mongodb.svg
  mysql_fdw:
    enabled: true
    schema_name: mysql_fdw
    name: MySQL
    icon: mysql.svg
  oracle_fdw:
    enabled: true
    schema_name: oracle_fdw
    name: Oracle
    icon: oracle.svg
  postgres_fdw:
    enabled: true
    schema_name: postgres_fdw
    name: Postgres
    icon: postgresql.svg
  sqlite_fdw:
    enabled: true
    schema_name: sqlite_fdw
    name: SQLite
    icon: sqlite.svg
  tds_fdw:
    enabled: true
    schema_name: tds_fdw
    name: SQL Server
    icon: mssql.svg


# FDW options template
#
# <option> =
#   option:
#     default:
#     description:
#
# <categories> =
#   foreign_server:
#     <option>
#   user_mapping:
#     <option>
#   foreign_table:
#     <option>
#   import_foreign_schema:
#     <option>
#
# fdw_name:
#   <categories>
#   advanced:
#     <categories>

# FDW options
fdw_options:
  file_fdw:
    foreign_server:
      filename:
      program:

  mongo_fdw:
    foreign_server:
      address:
      port: 27017
      authentication_database: admin

  mysql_fdw:
    foreign_server:
      host:
        default: 127.0.0.1
        description: Address or hostname of the MySQL server. Defaults to 127.0.0.1
      port:
        default: 3306
        description: Port number of the MySQL server. Defaults to 3306

    user_mapping:
      username:
        default:
        description: Username to use when connecting to MySQL.
      password:
        default:
        description: Password to authenticate to the MySQL server with.

    import_foreign_schema:
      import_default:
        default: false
        description: >
          This option controls whether column DEFAULT expressions are included in the definitions
          of foreign tables imported from a foreign server. The default is false.
      import_not_null:
        default: true
        description: >
          This option controls whether column NOT NULL constraints are included in the definitions
          of foreign tables imported from a foreign server. The default is true.
      import_enum_as_text:
        default: false
        description: >
          This option can be used to map MySQL ENUM type to TEXT type in the definitions
          of foreign tables, otherwise emit a warning for type to be created. The default is false.
      import_generated:
        default: true
        description: >
          This option controls whether GENERATED column expressions are included in the definitions
          of foreign tables imported from a foreign server or not. The default is true.
          The IMPORT will fail altogether if an imported generated expression
          uses a function or operator that does not exist on PostgreSQL.

    advanced:
      foreign_server:
        secure_auth:
          default: true
          description: Enable or disable secure authentication. Default is true
        init_command:
          default:
          description: SQL statement to execute when connecting to the MySQL server.
        reconnect:
          default: false
          description: >
            Enable or disable automatic reconnection to the MySQL server
            if the existing connection is found to have been lost. Default is false.



  oracle_fdw:
    foreign_server:
      dbserver:

  sqlite_fdw:
    foreign_server:
      database:

  tds_fdw:
    foreign_server:
      servername:
      port: 1433
      database:
