# validation schema: schema.yaml

postgres:

# true - extension is installed
# false - extension is not installed automatically. but still listed in pg_available_extensions and could be installed manually
fdw_list:
  file_fdw:
  mongo_fdw:
  mysql_fdw: false
  oracle_fdw:
  postgres_fdw:
  sqlite_fdw: false
  tds_fdw:
    schema_name: mssql
